# Generated by Django 3.0 on 2020-09-21 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 22, 49, 57, 991956), verbose_name='Fecha de publicacion'),
        ),
    ]
